"""
Consider all integer combinations of a**b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

If they are then placed in numerical order, with any repeats removed, we get
a sequence of 15 distinct terms.

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100
and 2 ≤ b ≤ 100?
"""

import numpy as np

def isprime(n):
    for i in range(2,n//2+1):
        if not n%i:
            return 0
    return 1

primes = []
for i in range(2,101):
    if isprime(i):
        primes.append(i)

def factor(n):
    global primes
    factors = [[],[]]
    for i in primes:
        n_i = 0
        n_tmp = n
        while (not n_tmp%i):
            n_i += 1
            n_tmp = n_tmp/i
        if n_i>0:
            factors[0].append(i)
            factors[1].append(n_i)
    return factors[0],factors[1]
c = []
for i in range(2,101):
    a,b = factor(i)
    c.append[a]
    print(c)
